
interface _GlobalComponents {
      'Box': typeof import("../components/Box.vue")['default']
    'IconsArrowLeft': typeof import("../components/Icons/ArrowLeft.vue")['default']
    'IconsChat': typeof import("../components/Icons/Chat.vue")['default']
    'IconsClose': typeof import("../components/Icons/Close.vue")['default']
    'IconsCopy': typeof import("../components/Icons/Copy.vue")['default']
    'IconsLoading': typeof import("../components/Icons/Loading.vue")['default']
    'Standby': typeof import("../components/Standby.vue")['default']
    'Widget': typeof import("../components/Widget.vue")['default']
    'WizardError': typeof import("../components/Wizard/Error.vue")['default']
    'Wizard': typeof import("../components/Wizard/Index.vue")['default']
    'WizardSelectFeedbackType': typeof import("../components/Wizard/SelectFeedbackType.vue")['default']
    'WizardSuccess': typeof import("../components/Wizard/Success.vue")['default']
    'WizardWriteFeedback': typeof import("../components/Wizard/WriteFeedback.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyBox': typeof import("../components/Box.vue")['default']
    'LazyIconsArrowLeft': typeof import("../components/Icons/ArrowLeft.vue")['default']
    'LazyIconsChat': typeof import("../components/Icons/Chat.vue")['default']
    'LazyIconsClose': typeof import("../components/Icons/Close.vue")['default']
    'LazyIconsCopy': typeof import("../components/Icons/Copy.vue")['default']
    'LazyIconsLoading': typeof import("../components/Icons/Loading.vue")['default']
    'LazyStandby': typeof import("../components/Standby.vue")['default']
    'LazyWidget': typeof import("../components/Widget.vue")['default']
    'LazyWizardError': typeof import("../components/Wizard/Error.vue")['default']
    'LazyWizard': typeof import("../components/Wizard/Index.vue")['default']
    'LazyWizardSelectFeedbackType': typeof import("../components/Wizard/SelectFeedbackType.vue")['default']
    'LazyWizardSuccess': typeof import("../components/Wizard/Success.vue")['default']
    'LazyWizardWriteFeedback': typeof import("../components/Wizard/WriteFeedback.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Box: typeof import("../components/Box.vue")['default']
export const IconsArrowLeft: typeof import("../components/Icons/ArrowLeft.vue")['default']
export const IconsChat: typeof import("../components/Icons/Chat.vue")['default']
export const IconsClose: typeof import("../components/Icons/Close.vue")['default']
export const IconsCopy: typeof import("../components/Icons/Copy.vue")['default']
export const IconsLoading: typeof import("../components/Icons/Loading.vue")['default']
export const Standby: typeof import("../components/Standby.vue")['default']
export const Widget: typeof import("../components/Widget.vue")['default']
export const WizardError: typeof import("../components/Wizard/Error.vue")['default']
export const Wizard: typeof import("../components/Wizard/Index.vue")['default']
export const WizardSelectFeedbackType: typeof import("../components/Wizard/SelectFeedbackType.vue")['default']
export const WizardSuccess: typeof import("../components/Wizard/Success.vue")['default']
export const WizardWriteFeedback: typeof import("../components/Wizard/WriteFeedback.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyBox: typeof import("../components/Box.vue")['default']
export const LazyIconsArrowLeft: typeof import("../components/Icons/ArrowLeft.vue")['default']
export const LazyIconsChat: typeof import("../components/Icons/Chat.vue")['default']
export const LazyIconsClose: typeof import("../components/Icons/Close.vue")['default']
export const LazyIconsCopy: typeof import("../components/Icons/Copy.vue")['default']
export const LazyIconsLoading: typeof import("../components/Icons/Loading.vue")['default']
export const LazyStandby: typeof import("../components/Standby.vue")['default']
export const LazyWidget: typeof import("../components/Widget.vue")['default']
export const LazyWizardError: typeof import("../components/Wizard/Error.vue")['default']
export const LazyWizard: typeof import("../components/Wizard/Index.vue")['default']
export const LazyWizardSelectFeedbackType: typeof import("../components/Wizard/SelectFeedbackType.vue")['default']
export const LazyWizardSuccess: typeof import("../components/Wizard/Success.vue")['default']
export const LazyWizardWriteFeedback: typeof import("../components/Wizard/WriteFeedback.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
